export const OPEN_SOCIAL_LOGIN_MODAL = "OPEN_SOCIAL_LOGIN_MODAL";
export const CLOSE_SOCIAL_LOGIN_MODAL = "CLOSE_SOCIAL_LOGIN_MODAL";
export const FB_LOGIN_SUCCESS = "FB_LOGIN_SUCCESS";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const FB_LOGOUT_SUCCESS = "FB_LOGOUT_SUCCESS";
